import type { Product, BlogPost, Promotion, Order, Novedad } from '@/types'

const PLACEHOLDER_CARD = 'https://placehold.co/300x420/1A2338/6BB8EC?text=TCG+Card'
const PLACEHOLDER_WIDE = 'https://placehold.co/800x400/1A2338/6BB8EC?text=Double-I+TCG'
const PLACEHOLDER_PACK = 'https://placehold.co/300x420/1A2338/6BB8EC?text=Booster+Pack'
const PLACEHOLDER_BOX = 'https://placehold.co/300x420/1A2338/6BB8EC?text=Booster+Box'
const PLACEHOLDER_ETB = 'https://placehold.co/300x420/1A2338/6BB8EC?text=ETB'
const PLACEHOLDER_ACC = 'https://placehold.co/300x420/1E3054/6BB8EC?text=Accesorio'

export const MOCK_PRODUCTS: Product[] = [
  // — Pokémon singles —
  {
    id: '1',
    slug: 'charizard-holo-base-set-1ed',
    name: 'Charizard Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 45000,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '4/102',
    isActive: true,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    salesCount: 3,
  },
  {
    id: '2',
    slug: 'pikachu-base-set-ilimitada',
    name: 'Pikachu',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 350,
    stock: 8,
    images: [PLACEHOLDER_CARD],
    cardNumber: '58/102',
    isActive: true,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    salesCount: 22,
  },
  {
    id: '3',
    slug: 'dark-magician-lob-1ed',
    name: 'Dark Magician',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 1200,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-005',
    isActive: true,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    salesCount: 15,
  },
  {
    id: '4',
    slug: 'blue-eyes-white-dragon-lob',
    name: 'Blue-Eyes White Dragon',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'secret_rare',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 8500,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-001',
    isActive: true,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    salesCount: 8,
  },
  {
    id: '5',
    slug: 'elsa-queen-lorcana-1st',
    name: 'Elsa — Snow Queen',
    franchise: 'lorcana',
    productType: 'single',
    set: 'The First Chapter',
    rarity: 'full_art',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 950,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    cardNumber: '43/204',
    isActive: true,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    salesCount: 11,
  },
  {
    id: '6',
    slug: 'blastoise-holo-base-set',
    name: 'Blastoise Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'lightly_played',
    variant: 'holo',
    language: 'en',
    price: 1800,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '2/102',
    isActive: true,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    salesCount: 5,
  },
  {
    id: '7',
    slug: 'exodia-the-forbidden-one-lob',
    name: 'Exodia the Forbidden One',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 3200,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-124',
    isActive: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    salesCount: 7,
  },
  {
    id: '8',
    slug: 'simba-lorcana-rise-floodborn',
    name: 'Simba — King Returned',
    franchise: 'lorcana',
    productType: 'single',
    set: 'Rise of the Floodborn',
    rarity: 'prismatic',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 2100,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: '119/204',
    isActive: true,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    salesCount: 9,
  },
  {
    id: '9',
    slug: 'venusaur-holo-base-set',
    name: 'Venusaur Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 2200,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '15/102',
    isActive: true,
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    salesCount: 6,
  },
  {
    id: '10',
    slug: 'mirror-force-sdk',
    name: 'Mirror Force',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Starter Deck Kaiba',
    rarity: 'secret_rare',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 1750,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'SDK-E007',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    salesCount: 12,
  },
  {
    id: '11',
    slug: 'pikachu-birthday-promo',
    name: 'Pikachu Birthday Promo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'WB Kids Promo',
    rarity: 'full_art',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 3500,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '24',
    isActive: true,
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    salesCount: 2,
  },
  {
    id: '12',
    slug: 'mickey-mouse-true-friend-lorcana',
    name: 'Mickey Mouse — True Friend',
    franchise: 'lorcana',
    productType: 'single',
    set: 'The First Chapter',
    rarity: 'prismatic',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 4800,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '89/204',
    isActive: true,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    salesCount: 18,
  },
  // — Pokémon singles (más) —
  {
    id: '13',
    slug: 'mewtwo-holo-base-set',
    name: 'Mewtwo Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 3800,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: '10/102',
    isActive: true,
    createdAt: new Date(Date.now() - 13 * 86400000).toISOString(),
    salesCount: 14,
  },
  {
    id: '14',
    slug: 'gengar-holo-fossil',
    name: 'Gengar Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Fossil',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 2600,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '5/62',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    salesCount: 10,
  },
  {
    id: '15',
    slug: 'alakazam-holo-base-set',
    name: 'Alakazam Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'lightly_played',
    variant: 'holo',
    language: 'en',
    price: 1400,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    cardNumber: '1/102',
    isActive: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    salesCount: 6,
  },
  {
    id: '16',
    slug: 'raichu-holo-base-set',
    name: 'Raichu Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 1750,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '14/102',
    isActive: true,
    createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
    salesCount: 8,
  },
  {
    id: '17',
    slug: 'gyarados-holo-base-set',
    name: 'Gyarados Holo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 2100,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: '6/102',
    isActive: true,
    createdAt: new Date(Date.now() - 17 * 86400000).toISOString(),
    salesCount: 9,
  },
  {
    id: '18',
    slug: 'snorlax-jungle',
    name: 'Snorlax',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Jungle',
    rarity: 'poco_comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 480,
    stock: 7,
    images: [PLACEHOLDER_CARD],
    cardNumber: '11/64',
    isActive: true,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    salesCount: 20,
  },
  {
    id: '19',
    slug: 'mew-black-star-promo',
    name: 'Mew — Black Star Promo',
    franchise: 'pokemon',
    productType: 'single',
    set: 'Black Star Promos',
    rarity: 'full_art',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 5200,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '8',
    isActive: true,
    createdAt: new Date(Date.now() - 19 * 86400000).toISOString(),
    salesCount: 4,
  },
  // — Yu-Gi-Oh! singles —
  {
    id: '20',
    slug: 'pot-of-greed-lob',
    name: 'Pot of Greed',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 890,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-119',
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    salesCount: 17,
  },
  {
    id: '21',
    slug: 'jinzo-sdk',
    name: 'Jinzo',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Starter Deck Kaiba',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 2400,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'SDK-030',
    isActive: true,
    createdAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    salesCount: 11,
  },
  {
    id: '22',
    slug: 'change-of-heart-lob',
    name: 'Change of Heart',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'rara',
    edition: 'primera',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 650,
    stock: 4,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-101',
    isActive: true,
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    salesCount: 13,
  },
  {
    id: '23',
    slug: 'monster-reborn-lob',
    name: 'Monster Reborn',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 750,
    stock: 5,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-118',
    isActive: true,
    createdAt: new Date(Date.now() - 23 * 86400000).toISOString(),
    salesCount: 16,
  },
  {
    id: '24',
    slug: 'raigeki-lob',
    name: 'Raigeki',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'secret_rare',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 3100,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-115',
    isActive: true,
    createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
    salesCount: 7,
  },
  {
    id: '25',
    slug: 'swords-revealing-light-lob',
    name: 'Swords of Revealing Light',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'poco_comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 280,
    stock: 10,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-104',
    isActive: true,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    salesCount: 25,
  },
  {
    id: '26',
    slug: 'black-skull-dragon-mrd',
    name: 'Black Skull Dragon',
    franchise: 'yugioh',
    productType: 'single',
    set: 'Metal Raiders',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'lightly_played',
    variant: 'holo',
    language: 'en',
    price: 1900,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'MRD-018',
    isActive: true,
    createdAt: new Date(Date.now() - 26 * 86400000).toISOString(),
    salesCount: 5,
  },
  // — Lorcana singles —
  {
    id: '27',
    slug: 'maui-hero-lorcana',
    name: 'Maui — Hero to All',
    franchise: 'lorcana',
    productType: 'single',
    set: 'The First Chapter',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 1250,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    cardNumber: '104/204',
    isActive: true,
    createdAt: new Date(Date.now() - 27 * 86400000).toISOString(),
    salesCount: 12,
  },
  {
    id: '28',
    slug: 'moana-wayfinder-lorcana',
    name: 'Moana — Chosen by the Ocean',
    franchise: 'lorcana',
    productType: 'single',
    set: 'Rise of the Floodborn',
    rarity: 'full_art',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 1800,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: '111/204',
    isActive: true,
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    salesCount: 9,
  },
  {
    id: '29',
    slug: 'stitch-carefree-surfer-lorcana',
    name: 'Stitch — Carefree Surfer',
    franchise: 'lorcana',
    productType: 'single',
    set: 'The First Chapter',
    rarity: 'rara',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 420,
    stock: 6,
    images: [PLACEHOLDER_CARD],
    cardNumber: '172/204',
    isActive: true,
    createdAt: new Date(Date.now() - 29 * 86400000).toISOString(),
    salesCount: 21,
  },
  {
    id: '30',
    slug: 'tinker-bell-giant-fairy-lorcana',
    name: 'Tinker Bell — Giant Fairy',
    franchise: 'lorcana',
    productType: 'single',
    set: 'Rise of the Floodborn',
    rarity: 'prismatic',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 3400,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '25/204',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    salesCount: 6,
  },
  {
    id: '31',
    slug: 'ursula-sea-witch-lorcana',
    name: 'Ursula — Sea Witch',
    franchise: 'lorcana',
    productType: 'single',
    set: 'The First Chapter',
    rarity: 'secret_rare',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 7200,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '56/204',
    isActive: true,
    createdAt: new Date(Date.now() - 31 * 86400000).toISOString(),
    salesCount: 3,
  },
  {
    id: '32',
    slug: 'gaston-handsome-lorcana',
    name: 'Gaston — Handsome for All',
    franchise: 'lorcana',
    productType: 'single',
    set: 'Rise of the Floodborn',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 960,
    stock: 4,
    images: [PLACEHOLDER_CARD],
    cardNumber: '66/204',
    isActive: true,
    createdAt: new Date(Date.now() - 32 * 86400000).toISOString(),
    salesCount: 8,
  },
  // — Pokémon cartas gradeadas —
  {
    id: '33',
    slug: 'charizard-base-set-psa10',
    name: 'Charizard Base Set — PSA 10',
    franchise: 'pokemon',
    productType: 'graded',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 120000,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '4/102',
    description: 'Calificación PSA 10 Gem Mint. Slab sellado con número de certificado incluido.',
    isActive: true,
    createdAt: new Date(Date.now() - 33 * 86400000).toISOString(),
    salesCount: 1,
  },
  {
    id: '34',
    slug: 'pikachu-illustrator-bgs9',
    name: 'Pikachu Illustrator — BGS 9',
    franchise: 'pokemon',
    productType: 'graded',
    set: 'Pikachu Illustrator Promo',
    rarity: 'prismatic',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'jp',
    price: 450000,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    description: 'Una de las cartas más raras del mundo. Calificación BGS 9. Certificado auténtico.',
    isActive: true,
    createdAt: new Date(Date.now() - 34 * 86400000).toISOString(),
    salesCount: 0,
  },
  // — Pokémon productos sellados —
  {
    id: '35',
    slug: 'pokemon-sv-scarlet-violet-booster-pack',
    name: 'Pokémon TCG — Scarlet & Violet Booster Pack',
    franchise: 'pokemon',
    productType: 'booster_pack',
    set: 'Scarlet & Violet',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 180,
    stock: 50,
    images: [PLACEHOLDER_PACK],
    description: '10 cartas por paquete. Posibilidad de cartas ex y cartas especiales.',
    isActive: true,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    salesCount: 64,
  },
  {
    id: '36',
    slug: 'pokemon-sv-paldea-evolved-booster-box',
    name: 'Pokémon TCG — Paldea Evolved Booster Box',
    franchise: 'pokemon',
    productType: 'booster_box',
    set: 'Paldea Evolved',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 3200,
    stock: 8,
    images: [PLACEHOLDER_BOX],
    description: '36 booster packs por caja. Sellada de fábrica.',
    isActive: true,
    createdAt: new Date(Date.now() - 36 * 86400000).toISOString(),
    salesCount: 12,
  },
  {
    id: '37',
    slug: 'pokemon-sv-etb-scarlet-violet',
    name: 'Pokémon TCG — Scarlet & Violet Elite Trainer Box',
    franchise: 'pokemon',
    productType: 'elite_trainer_box',
    set: 'Scarlet & Violet',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 1450,
    stock: 10,
    images: [PLACEHOLDER_ETB],
    description: 'Incluye 9 booster packs, sleeves oficiales, dados de energía, divisores y más.',
    isActive: true,
    createdAt: new Date(Date.now() - 37 * 86400000).toISOString(),
    salesCount: 18,
  },
  {
    id: '38',
    slug: 'pokemon-151-etb',
    name: 'Pokémon 151 — Elite Trainer Box',
    franchise: 'pokemon',
    productType: 'elite_trainer_box',
    set: 'Pokémon 151',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 1850,
    stock: 5,
    images: [PLACEHOLDER_ETB],
    description: 'Edición especial celebrando los 151 Pokémon originales. Muy buscada.',
    isActive: true,
    createdAt: new Date(Date.now() - 38 * 86400000).toISOString(),
    salesCount: 22,
  },
  {
    id: '39',
    slug: 'pokemon-sv-build-battle-box',
    name: 'Pokémon TCG — Scarlet & Violet Build & Battle Box',
    franchise: 'pokemon',
    productType: 'build_and_battle',
    set: 'Scarlet & Violet',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 650,
    stock: 15,
    images: [PLACEHOLDER_BOX],
    description: '4 booster packs + mazo pre-construido de 23 cartas. Ideal para empezar.',
    isActive: true,
    createdAt: new Date(Date.now() - 39 * 86400000).toISOString(),
    salesCount: 9,
  },
  {
    id: '40',
    slug: 'pokemon-sv-booster-bundle',
    name: 'Pokémon TCG — Stellar Crown Booster Bundle',
    franchise: 'pokemon',
    productType: 'booster_bundle',
    set: 'Stellar Crown',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 950,
    stock: 12,
    images: [PLACEHOLDER_PACK],
    description: '6 booster packs del set Stellar Crown.',
    isActive: true,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    salesCount: 15,
  },
  // — Lorcana productos sellados —
  {
    id: '41',
    slug: 'lorcana-inklands-booster-pack',
    name: 'Disney Lorcana — Into the Inklands Booster Pack',
    franchise: 'lorcana',
    productType: 'booster_pack',
    set: 'Into the Inklands',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 200,
    stock: 40,
    images: [PLACEHOLDER_PACK],
    description: '12 cartas por paquete. Incluye posibilidad de cartas enchanted.',
    isActive: true,
    createdAt: new Date(Date.now() - 41 * 86400000).toISOString(),
    salesCount: 35,
  },
  {
    id: '42',
    slug: 'lorcana-first-chapter-starter-deck',
    name: 'Disney Lorcana — The First Chapter Starter Deck',
    franchise: 'lorcana',
    productType: 'starter_deck',
    set: 'The First Chapter',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 680,
    stock: 8,
    images: [PLACEHOLDER_PACK],
    description: 'Mazo de inicio de 60 cartas. Ideal para jugadores nuevos.',
    isActive: true,
    createdAt: new Date(Date.now() - 42 * 86400000).toISOString(),
    salesCount: 14,
  },
  {
    id: '43',
    slug: 'lorcana-sleeves-official',
    name: 'Disney Lorcana — Sleeves Oficiales',
    franchise: 'lorcana',
    productType: 'sleeves',
    set: 'Accesorios',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 220,
    stock: 25,
    images: [PLACEHOLDER_ACC],
    description: 'Paquete de 65 sleeves oficiales Disney Lorcana.',
    isActive: true,
    createdAt: new Date(Date.now() - 43 * 86400000).toISOString(),
    salesCount: 28,
  },
  // — Magic: The Gathering —
  {
    id: '44',
    slug: 'magic-bloomburrow-booster-pack',
    name: 'Magic: The Gathering — Bloomburrow Booster Pack',
    franchise: 'magic',
    productType: 'booster_pack',
    set: 'Bloomburrow',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 220,
    stock: 30,
    images: [PLACEHOLDER_PACK],
    description: '14 cartas por paquete (Play Booster). Nuevo formato de booster 2024.',
    isActive: true,
    createdAt: new Date(Date.now() - 44 * 86400000).toISOString(),
    salesCount: 42,
  },
  {
    id: '45',
    slug: 'magic-modern-horizons-3-booster-box',
    name: 'Magic: The Gathering — Modern Horizons 3 Booster Box',
    franchise: 'magic',
    productType: 'booster_box',
    set: 'Modern Horizons 3',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 4800,
    stock: 4,
    images: [PLACEHOLDER_BOX],
    description: '36 Play Boosters. Set altamente valorado para Modern y Legacy.',
    isActive: true,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    salesCount: 6,
  },
  {
    id: '46',
    slug: 'magic-commander-precon-bloomburrow',
    name: 'Magic: The Gathering — Commander Deck Bloomburrow',
    franchise: 'magic',
    productType: 'starter_deck',
    set: 'Bloomburrow Commander',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 1200,
    stock: 7,
    images: [PLACEHOLDER_PACK],
    description: 'Mazo Commander pre-construido de 100 cartas, listo para jugar.',
    isActive: true,
    createdAt: new Date(Date.now() - 46 * 86400000).toISOString(),
    salesCount: 11,
  },
  {
    id: '47',
    slug: 'magic-lightning-bolt-single',
    name: 'Lightning Bolt',
    franchise: 'magic',
    productType: 'single',
    set: 'Alpha / Beta / Unlimited',
    rarity: 'comun',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 1800,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: '161',
    description: 'Alpha Unlimited Lightning Bolt. Una de las cartas más icónicas de MTG.',
    isActive: true,
    createdAt: new Date(Date.now() - 47 * 86400000).toISOString(),
    salesCount: 3,
  },
  {
    id: '48',
    slug: 'magic-bloomburrow-collectors-booster',
    name: 'Magic: The Gathering — Bloomburrow Collector Booster',
    franchise: 'magic',
    productType: 'booster_pack',
    set: 'Bloomburrow',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 780,
    stock: 18,
    images: [PLACEHOLDER_PACK],
    description: '15 cartas premium: foils, alternativas art, serialized. Máxima calidad.',
    isActive: true,
    createdAt: new Date(Date.now() - 48 * 86400000).toISOString(),
    salesCount: 19,
  },
  // — Accesorios genéricos —
  {
    id: '49',
    slug: 'dragon-shield-matte-sleeves',
    name: 'Dragon Shield — Matte Sleeves (100u)',
    franchise: 'accessories',
    productType: 'sleeves',
    set: 'Accesorios',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 320,
    stock: 35,
    images: [PLACEHOLDER_ACC],
    description: '100 sleeves Dragon Shield Matte. Compatibles con cartas TCG estándar.',
    isActive: true,
    createdAt: new Date(Date.now() - 49 * 86400000).toISOString(),
    salesCount: 55,
  },
  {
    id: '50',
    slug: 'ultra-pro-playmat-tcg',
    name: 'Ultra PRO — Playmat Standard',
    franchise: 'accessories',
    productType: 'playmat',
    set: 'Accesorios',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 480,
    stock: 12,
    images: [PLACEHOLDER_ACC],
    description: 'Tapete de juego 60×35cm. Superficie antideslizante. Compatible con todos los TCG.',
    isActive: true,
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    salesCount: 30,
  },
  {
    id: '51',
    slug: 'chessex-dice-set-tcg',
    name: 'Chessex — Set de Dados TCG (7 pzas)',
    franchise: 'accessories',
    productType: 'dice',
    set: 'Accesorios',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 180,
    stock: 20,
    images: [PLACEHOLDER_ACC],
    description: 'Set completo: d4, d6, d8, d10, d12, d20 y d%. Ideal para RPG y TCG.',
    isActive: true,
    createdAt: new Date(Date.now() - 51 * 86400000).toISOString(),
    salesCount: 40,
  },
  {
    id: '52',
    slug: 'ultra-pro-deck-box-standard',
    name: 'Ultra PRO — Deck Box Standard',
    franchise: 'accessories',
    productType: 'deck_box',
    set: 'Accesorios',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 150,
    stock: 30,
    images: [PLACEHOLDER_ACC],
    description: 'Deck box con cierre magnético. Capacidad para 100 cartas con sleeve.',
    isActive: true,
    createdAt: new Date(Date.now() - 52 * 86400000).toISOString(),
    salesCount: 48,
  },
  {
    id: '53',
    slug: 'ultra-pro-binder-9pocket',
    name: 'Ultra PRO — Binder 9 Pockets (360 cartas)',
    franchise: 'accessories',
    productType: 'binder',
    set: 'Accesorios',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 350,
    stock: 18,
    images: [PLACEHOLDER_ACC],
    description: 'Álbum de 9 bolsillos por página. Capacidad total: 360 cartas.',
    isActive: true,
    createdAt: new Date(Date.now() - 53 * 86400000).toISOString(),
    salesCount: 33,
  },
  {
    id: '54',
    slug: 'pokemon-tin-charizard-sv',
    name: 'Pokémon TCG — Charizard ex Tin',
    franchise: 'pokemon',
    productType: 'tin',
    set: 'Scarlet & Violet',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 780,
    stock: 9,
    images: [PLACEHOLDER_ETB],
    description: 'Tin metálica con promo Charizard ex + 4 booster packs.',
    isActive: true,
    createdAt: new Date(Date.now() - 54 * 86400000).toISOString(),
    salesCount: 16,
  },
  {
    id: '55',
    slug: 'lorcana-treasure-trove-box-set',
    name: 'Disney Lorcana — Treasure Trove Box Set',
    franchise: 'lorcana',
    productType: 'box_set',
    set: 'The First Chapter',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 1600,
    stock: 5,
    images: [PLACEHOLDER_BOX],
    description: 'Box set con cartas exclusivas, dados de tinta y guía del juego.',
    isActive: true,
    createdAt: new Date(Date.now() - 55 * 86400000).toISOString(),
    salesCount: 7,
  },
]

export const MOCK_NOVEDADES: Novedad[] = [
  {
    id: 'nov-1',
    title: 'Pokémon 151 ETB — Edición Especial',
    image: 'https://placehold.co/900x560/CC0000/FFFFFF?text=Pokemon+151+Elite+Trainer+Box',
    productSlug: 'pokemon-151-etb',
    text: 'Celebrando los primeros 151 Pokémon con una edición premium limitada.',
    order: 1,
    isActive: true,
  },
  {
    id: 'nov-2',
    title: 'Lorcana Into The Inklands — Ya disponible',
    image: 'https://placehold.co/900x560/1A2338/6BB8EC?text=Lorcana+Into+The+Inklands',
    productSlug: 'lorcana-inklands-booster-pack',
    text: 'Explora nuevos mundos en el 4to set de Disney Lorcana.',
    order: 2,
    isActive: true,
  },
  {
    id: 'nov-3',
    title: 'Magic: The Gathering — Bloomburrow',
    image: 'https://placehold.co/900x560/1A0A2E/C8950A?text=MTG+Bloomburrow',
    productSlug: 'magic-bloomburrow-booster-pack',
    text: 'El set más esperado del año ya está en catálogo.',
    order: 3,
    isActive: true,
  },
  {
    id: 'nov-4',
    title: 'Dragon Shield Matte — Nuevos colores',
    image: 'https://placehold.co/900x560/1E3054/C8D8F0?text=Dragon+Shield+Matte+Sleeves',
    productSlug: 'dragon-shield-matte-sleeves',
    text: 'Protege tu colección con los mejores sleeves del mercado.',
    order: 4,
    isActive: true,
  },
  {
    id: 'nov-5',
    title: 'Charizard Base Set PSA 10 — Ultra raro',
    image: 'https://placehold.co/900x560/8B0000/FFD700?text=Charizard+PSA+10',
    productSlug: 'charizard-base-set-psa10',
    text: 'Una joya del coleccionismo certificada en calidad Gem Mint.',
    order: 5,
    isActive: true,
  },
  {
    id: 'nov-6',
    title: 'Modern Horizons 3 — Booster Box',
    image: 'https://placehold.co/900x560/0D1A3A/6BB8EC?text=Modern+Horizons+3+Box',
    productSlug: 'magic-modern-horizons-3-booster-box',
    text: 'El set más poderoso de Modern en años. Imprescindible para competitivos.',
    order: 6,
    isActive: true,
  },
]

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: '1',
    title: '¡Semana Pokémon!',
    description: '15% de descuento en todas las cartas Pokémon hasta el domingo',
    discountType: 'porcentaje',
    discountValue: 15,
    validFrom: new Date().toISOString(),
    validTo: new Date(Date.now() + 7 * 86400000).toISOString(),
    isActive: true,
    image: PLACEHOLDER_WIDE,
  },
  {
    id: '2',
    title: 'Envío gratis en compras +$800',
    description: 'En pedidos mayores a $800 MXN, el envío corre por nuestra cuenta',
    discountType: 'monto',
    discountValue: 0,
    validFrom: new Date().toISOString(),
    validTo: new Date(Date.now() + 30 * 86400000).toISOString(),
    isActive: true,
  },
]

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'como-identificar-cartas-primera-edicion-pokemon',
    title: 'Cómo identificar cartas de 1ª Edición de Pokémon',
    excerpt: 'Aprende los detalles que diferencian una carta de primera edición de una ilimitada y por qué su valor es tan distinto.',
    body: '<p>Guía completa para identificar cartas de primera edición...</p>',
    image: PLACEHOLDER_WIDE,
    category: 'pokemon',
    tags: ['guía', 'primera edición', 'coleccionismo'],
    publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    isDraft: false,
    metaTitle: 'Cómo identificar cartas 1ª Edición Pokémon | Double-I TCG',
    metaDescription: 'Guía completa para identificar cartas de primera edición de Pokémon.',
  },
  {
    id: '2',
    slug: 'lorcana-rise-of-the-floodborn-review',
    title: 'Lorcana Rise of the Floodborn: las cartas que debes tener',
    excerpt: 'Analizamos las cartas más valiosas y jugables del segundo set de Disney Lorcana.',
    body: '<p>El segundo set de Lorcana llegó cargado de sorpresas...</p>',
    image: PLACEHOLDER_WIDE,
    category: 'lorcana',
    tags: ['lorcana', 'set review', 'rise of the floodborn'],
    publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    isDraft: false,
  },
  {
    id: '3',
    slug: 'guia-condicion-cartas-tcg',
    title: 'Mint, Near Mint, Played: Guía de condición para coleccionistas',
    excerpt: 'Entender la condición de una carta es fundamental para comprar y vender con confianza.',
    body: '<p>La condición de una carta determina su valor...</p>',
    image: PLACEHOLDER_WIDE,
    category: 'general',
    tags: ['guía', 'condición', 'grading'],
    publishedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    isDraft: false,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: '1',
    orderNumber: 'DI-2026-0001',
    status: 'enviado',
    items: [
      { productId: '1', name: 'Charizard Holo', price: 45000, quantity: 1, image: PLACEHOLDER_CARD },
    ],
    subtotal: 45000,
    shippingCost: 180,
    total: 45180,
    shippingOption: { id: 'dhl-1', carrier: 'dhl', service: 'DHL Express', price: 180, eta: '2-3 días' },
    trackingNumber: 'DHL12345678MX',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    customer: { name: 'Carlos Ramírez', email: 'carlos@example.com', phone: '5512345678' },
    address: { street: 'Av. Insurgentes Sur', number: '123', colonia: 'Roma Norte', city: 'Ciudad de México', state: 'CDMX', zip: '06700' },
  },
]
