import type { Product, BlogPost, Promotion, Order } from '@/types'

const PLACEHOLDER_CARD = 'https://placehold.co/300x420/1E0E40/6BB8EC?text=TCG+Card'
const PLACEHOLDER_WIDE = 'https://placehold.co/800x400/1E0E40/6BB8EC?text=Double-I+TCG'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'charizard-holo-base-set-1ed',
    name: 'Charizard Holo',
    franchise: 'pokemon',
    productType: 'carta',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 45000,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '4/102',
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    salesCount: 3,
  },
  {
    id: '2',
    slug: 'pikachu-base-set-ilimitada',
    name: 'Pikachu',
    franchise: 'pokemon',
    productType: 'carta',
    set: 'Base Set',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 350,
    stock: 8,
    images: [PLACEHOLDER_CARD],
    cardNumber: '58/102',
    isActive: true,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    salesCount: 22,
  },
  {
    id: '3',
    slug: 'dark-magician-lob-1ed',
    name: 'Dark Magician',
    franchise: 'yugioh',
    productType: 'carta',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 1200,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-005',
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    salesCount: 15,
  },
  {
    id: '4',
    slug: 'blue-eyes-white-dragon-lob',
    name: 'Blue-Eyes White Dragon',
    franchise: 'yugioh',
    productType: 'carta',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'secret_rare',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 8500,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-001',
    isActive: true,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    salesCount: 8,
  },
  {
    id: '5',
    slug: 'elsa-queen-lorcana-1st',
    name: 'Elsa — Snow Queen',
    franchise: 'lorcana',
    productType: 'carta',
    set: "The First Chapter",
    rarity: 'full_art',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 950,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    cardNumber: '43/204',
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    salesCount: 11,
  },
  {
    id: '6',
    slug: 'blastoise-holo-base-set',
    name: 'Blastoise Holo',
    franchise: 'pokemon',
    productType: 'carta',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'lightly_played',
    variant: 'holo',
    language: 'en',
    price: 1800,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '2/102',
    isActive: true,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    salesCount: 5,
  },
  {
    id: '7',
    slug: 'exodia-the-forbidden-one-lob',
    name: 'Exodia the Forbidden One',
    franchise: 'yugioh',
    productType: 'carta',
    set: 'Legend of Blue Eyes White Dragon',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 3200,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'LOB-124',
    isActive: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    salesCount: 7,
  },
  {
    id: '8',
    slug: 'simba-lorcana-rise-floodborn',
    name: 'Simba — King Returned',
    franchise: 'lorcana',
    productType: 'carta',
    set: 'Rise of the Floodborn',
    rarity: 'prismatic',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 2100,
    stock: 2,
    images: [PLACEHOLDER_CARD],
    cardNumber: '119/204',
    isActive: true,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    salesCount: 9,
  },
  {
    id: '9',
    slug: 'venusaur-holo-base-set',
    name: 'Venusaur Holo',
    franchise: 'pokemon',
    productType: 'carta',
    set: 'Base Set',
    rarity: 'ultra_rara',
    edition: 'ilimitada',
    condition: 'near_mint',
    variant: 'holo',
    language: 'en',
    price: 2200,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '15/102',
    isActive: true,
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    salesCount: 6,
  },
  {
    id: '10',
    slug: 'mirror-force-sdk',
    name: 'Mirror Force',
    franchise: 'yugioh',
    productType: 'carta',
    set: 'Starter Deck Kaiba',
    rarity: 'secret_rare',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 1750,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: 'SDK-E007',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    salesCount: 12,
  },
  {
    id: '11',
    slug: 'pikachu-birthday-promo',
    name: 'Pikachu Birthday Promo',
    franchise: 'pokemon',
    productType: 'carta',
    set: 'WB Kids Promo',
    rarity: 'full_art',
    edition: 'primera',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 3500,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '24',
    isActive: true,
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    salesCount: 2,
  },
  {
    id: '12',
    slug: 'mickey-mouse-true-friend-lorcana',
    name: 'Mickey Mouse — True Friend',
    franchise: 'lorcana',
    productType: 'carta',
    set: "The First Chapter",
    rarity: 'prismatic',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'holo',
    language: 'en',
    price: 4800,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    cardNumber: '89/204',
    isActive: true,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    salesCount: 18,
  },
  // Magic: The Gathering
  {
    id: 'mg1',
    slug: 'black-lotus-alpha-magic',
    name: 'Black Lotus',
    franchise: 'magic',
    productType: 'carta',
    set: 'Alpha',
    rarity: 'ultra_rara',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 950000,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    isNew: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    salesCount: 1,
  },
  {
    id: 'mg2',
    slug: 'lightning-bolt-alpha-magic',
    name: 'Lightning Bolt',
    franchise: 'magic',
    productType: 'carta',
    set: 'Alpha',
    rarity: 'comun',
    edition: 'primera',
    condition: 'near_mint',
    variant: 'standard',
    language: 'en',
    price: 4200,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 0.8 * 86400000).toISOString(),
    salesCount: 5,
  },
  {
    id: 'mg3',
    slug: 'underground-sea-dual-land-magic',
    name: 'Underground Sea',
    franchise: 'magic',
    productType: 'carta',
    set: 'Revised Edition',
    rarity: 'rara',
    edition: 'ilimitada',
    condition: 'lightly_played',
    variant: 'standard',
    language: 'en',
    price: 38000,
    stock: 1,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    isNew: false,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    salesCount: 3,
  },
  // Accesorios
  {
    id: '13',
    slug: 'sleeve-pikachu-pokemon-center',
    name: 'Sleeves Pikachu Pokémon Center',
    franchise: 'pokemon',
    productType: 'sleeve',
    set: 'Pokémon Center Exclusive',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 380,
    stock: 10,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    salesCount: 0,
  },
  {
    id: '14',
    slug: 'playmat-yugioh-dark-magician',
    name: 'Playmat Dark Magician',
    franchise: 'yugioh',
    productType: 'playmat',
    set: 'Konami Merchandise',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 850,
    stock: 5,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 0.3 * 86400000).toISOString(),
    salesCount: 0,
  },
  {
    id: '15',
    slug: 'etb-scarlet-violet-temporal-forces',
    name: 'ETB Temporal Forces',
    franchise: 'pokemon',
    productType: 'etb',
    set: 'Scarlet & Violet — Temporal Forces',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 1490,
    stock: 3,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    isNew: true,
    createdAt: new Date(Date.now() - 0.2 * 86400000).toISOString(),
    salesCount: 0,
  },
  {
    id: '16',
    slug: 'binder-lorcana-premium-9-pocket',
    name: 'Binder Premium 9-Pocket Lorcana',
    franchise: 'lorcana',
    productType: 'binder',
    set: 'Disney Lorcana Merchandise',
    rarity: 'comun',
    edition: 'ilimitada',
    condition: 'mint',
    variant: 'standard',
    language: 'en',
    price: 650,
    stock: 7,
    images: [PLACEHOLDER_CARD],
    isActive: true,
    createdAt: new Date(Date.now() - 13 * 86400000).toISOString(),
    salesCount: 4,
  },
]

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: '1',
    title: '¡Semana Pokémon!',
    description: '15% de descuento en todas las cartas Pokémon hasta el domingo',
    discountType: 'porcentaje',
    discountValue: 15,
    validFrom: new Date().toISOString(),
    validTo: new Date(Date.now() + 7 * 86400000).toISOString(),
    isActive: true,
    image: PLACEHOLDER_WIDE,
  },
  {
    id: '2',
    title: 'Envío gratis en compras +$800',
    description: 'En pedidos mayores a $800 MXN, el envío corre por nuestra cuenta',
    discountType: 'monto',
    discountValue: 0,
    validFrom: new Date().toISOString(),
    validTo: new Date(Date.now() + 30 * 86400000).toISOString(),
    isActive: true,
  },
]

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'como-identificar-cartas-primera-edicion-pokemon',
    title: 'Cómo identificar cartas de 1ª Edición de Pokémon',
    excerpt: 'Aprende los detalles que diferencian una carta de primera edición de una ilimitada y por qué su valor es tan distinto.',
    body: '<p>Guía completa para identificar cartas de primera edición...</p>',
    image: PLACEHOLDER_WIDE,
    category: 'pokemon',
    tags: ['guía', 'primera edición', 'coleccionismo'],
    publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    isDraft: false,
    metaTitle: 'Cómo identificar cartas 1ª Edición Pokémon | Double-I TCG',
    metaDescription: 'Guía completa para identificar cartas de primera edición de Pokémon.',
  },
  {
    id: '2',
    slug: 'lorcana-rise-of-the-floodborn-review',
    title: 'Lorcana Rise of the Floodborn: las cartas que debes tener',
    excerpt: 'Analizamos las cartas más valiosas y jugables del segundo set de Disney Lorcana.',
    body: '<p>El segundo set de Lorcana llegó cargado de sorpresas...</p>',
    image: PLACEHOLDER_WIDE,
    category: 'lorcana',
    tags: ['lorcana', 'set review', 'rise of the floodborn'],
    publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    isDraft: false,
  },
  {
    id: '3',
    slug: 'guia-condicion-cartas-tcg',
    title: 'Mint, Near Mint, Played: Guía de condición para coleccionistas',
    excerpt: 'Entender la condición de una carta es fundamental para comprar y vender con confianza.',
    body: '<p>La condición de una carta determina su valor...</p>',
    image: PLACEHOLDER_WIDE,
    category: 'general',
    tags: ['guía', 'condición', 'grading'],
    publishedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    isDraft: false,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: '1',
    orderNumber: 'DI-2026-0001',
    status: 'enviado',
    items: [
      { productId: '1', name: 'Charizard Holo', price: 45000, quantity: 1, image: PLACEHOLDER_CARD },
    ],
    subtotal: 45000,
    shippingCost: 180,
    total: 45180,
    shippingOption: { id: 'dhl-1', carrier: 'dhl', service: 'DHL Express', price: 180, eta: '2-3 días' },
    trackingNumber: 'DHL12345678MX',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    customer: { name: 'Carlos Ramírez', email: 'carlos@example.com', phone: '5512345678' },
    address: { street: 'Av. Insurgentes Sur', number: '123', colonia: 'Roma Norte', city: 'Ciudad de México', state: 'CDMX', zip: '06700' },
  },
]
